### ISSUE TITLE
Destroying jobs does not clear a workflow's submitted status

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/osc-machete#113]
Using `destroy` on a workflow's associated jobs does not reset the workflow status to `not_submitted`, using `clear`, however, does clear the workflow state.

```
irb(main):009:0> Workflow.last.jobs
  Workflow Load (5.1ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
  Job Load (3.7ms)  SELECT "jobs".* FROM "jobs"  WHERE "jobs"."workflow_id" = ?  [["workflow_id", 82]]
=> #<ActiveRecord::Associations::CollectionProxy [#<Job id: 27, workflow_id: 82, status: "Q", job_cache: {"sc
ript"=>"/users/appl/bmcmichael/ondemand/dev/myjobs/data/projects/default/66/pbs_script.sh", "pbsid"=>"9327595
.oak-batch.osc.edu", "host"=>"oakley"}, created_at: "2017-05-19 15:04:21", updated_at: "2017-05-19 15:04:21">
]>
irb(main):010:0> Workflow.last.jobs.destroy
  Workflow Load (3.0ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
=> []
irb(main):011:0> Workflow.last.submitted?  
  Workflow Load (1.7ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
  Job Load (1.7ms)  SELECT "jobs".* FROM "jobs"  WHERE "jobs"."workflow_id" = ?  [["workflow_id", 82]]
=> true
irb(main):012:0> Workflow.last.jobs.clear  
  Workflow Load (2.0ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
  SQL (8.5ms)  DELETE FROM "jobs" WHERE "jobs"."workflow_id" = ?  [["workflow_id", 82]]
=> #<ActiveRecord::Associations::CollectionProxy []>
irb(main):013:0> Workflow.last.submitted?
  Workflow Load (2.0ms)  SELECT  "workflows".* FROM "workflows"   ORDER BY "workflows"."id" DESC LIMIT 1
  Job Load (1.7ms)  SELECT "jobs".* FROM "jobs"  WHERE "jobs"."workflow_id" = ?  [["workflow_id", 82]]
=> false
```

I suspect that there is still a job relationship that is being retained after the `destroy` method or callbacks, which cause a call to `.submitted?` to return true because for the purposes of statusing: `nil == undetermined`, and an `undetermined` state is one which has been submitted. See: https://github.com/OSC/osc-machete/blob/master/lib/osc/machete/status.rb#L141

I'm not sure if this is expected behavior or not. I suspect it isn't.

**Comment by ericfranz** [comment]
You want `Workflow.last.jobs.destroy_all` or `Workflow.last.jobs.each(&:destroy)`. `Workflow.last.jobs.destroy` has no effect because `CollectionProxy#destroy` accepts the argument of the records to destroy.

http://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-destroy

vs

http://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html#method-i-destroy_all
